In [1]:
import torch

张量

In [34]:
x = torch.arange(12)

In [35]:
x.shape

torch.Size([12])

In [39]:
torch.sum(x)

tensor(66)

In [37]:
x.numel()

12

In [40]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [41]:
torch.zeros((2, 3, 4))
torch.ones((2, 3, 4))
torch.randn(3, 4)

tensor([[ 0.2320, -0.8318, -1.0005, -0.3860],
        [ 1.5943, -1.5283,  0.6228, -1.7536],
        [-0.2688, -0.9949, -0.6353,  0.7470]])

In [12]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [44]:
x = torch.tensor([1.0, 2, 4, 8]) 
y = torch.tensor([2, 2, 2, 2])

In [45]:
x+y,x-y,x/y,x*y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 2.,  4.,  8., 16.]))

In [46]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

张量拼接

In [47]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4)) 
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [48]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [49]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [50]:
X.sum()

tensor(66.)

索引和切片

In [21]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [22]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[1,2]

tensor(6.)

In [24]:
X[0:2, :]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

节省内存 原地存储

In [25]:
before = id(Y) 
Y=Y+X 
id(Y) == before # 自动分配了新的地址

False

In [27]:
Z = torch.zeros_like(Y) 
print('id(Z):', id(Z)) 
Z[:] = X + Y # 冒号的赋值,原地存储
print('id(Z):', id(Z))

id(Z): 2870689049552
id(Z): 2870689049552


转换为其他Python对象

In [52]:
A = X.numpy() # 变为numpy
B = torch.tensor(A) # 变为tensor
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [53]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)